#! /bin/sh
# Emails me the ip address of pi on ANY NETWORK UP.

set -e

# Don't bother to restart sshd when lo is configured.
if [ "$IFACE" = lo ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

# OpenSSH only cares about inet and inet6. Get ye gone, strange people
# still using ipx.
if [ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]; then
	exit 0
fi


hostname -I > /tmp/myip.txt

mail -s "Hello World From Your PI! :D" desaideep@gmail.com < /tmp/myip.txt
